# Classification using Casualties data

Introduction: 
    
#### In this notebook, we are comparing 11 classification algorithms to analyze the Casualties dataset over 3 years (2017, 2018, 2019).
    
1. Logistic Regression 
2. Logistic Regression with 10-fold CV 
3. Random Forests with 10-Fold
4. Polynomial Kernel SVM 
5. LinearSVC 
6. Decision Tree Classifier 
7. SGD Classifier 
8. OneVsRestClassifier SVC model
9. KNeighborsClassifier & GridSearchCV 
10. XGBoost 
11. AdaBoost

<br>***Note: This notebook is estimated to run for approximately 2+ hours.***

### Installation
1. brew install libomp
2. !pip install xgboost

In [2]:
#Importing all the libraries

import pandas as pd
import numpy as np
import sklearn
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import LinearSVC
from sklearn import svm
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import GridSearchCV
from sklearn import neighbors
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import GridSearchCV
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone

In [3]:
#Loading the preprocessed data for Casualities

df = pd.read_csv("data/data.csv")

In [4]:
df #checking what this dataframe df looks like

Accident_Index  Vehicle_Reference  Casualty_Reference  Casualty_Class  \
0       2019010128300                  1                   1               1   
1       2019010152270                  1                   1               1   
2       2019010155191                  2                   1               2   
3       2019010155192                  1                   1               3   
4       2019010155194                  1                   1               1   
...               ...                ...                 ...             ...   
458843  2017984121217                  1                   1               3   
458844  2017984121717                  1                   1               2   
458845  2017984122317                  1                   1               1   
458846  2017984122617                  1                   1               1   
458847  2017984122617                  2                   2               1   

        Sex_of_Casualty  Age_of_Casualty  Age_Band_of_Casualty  \
0                     1               58                     9   
1                     2               24                     5   
2                     2               21                     5   
3                     1               68                    10   
4                     2               47                     8   
...                 ...              ...                   ...   
458843                2               49                     8   
458844                1               22                     5   
458845                1               25                     5   
458846                1               49                     8   
458847                1               50                     8   

        Casualty_Severity  Pedestrian_Location  Pedestrian_Movement  \
0                       3                    0                    0   
1                       3                    0                    0   
2                       3                    0                    0   
3                       2                    5                    4   
4                       3                    0                    0   
...                   ...                  ...                  ...   
458843                  3                    9                    6   
458844                  3                    0                    0   
458845                  3                    0                    0   
458846                  3                    0                    0   
458847                  2                    0                    0   

        Car_Passenger  Bus_or_Coach_Passenger  \
0                   0                       0   
1                   0                       0   
2                   0                       0   
3                   0                       0   
4                   0                       0   
...               ...                     ...   
458843              0                       0   
458844              1                       0   
458845              0                       0   
458846              0                       0   
458847              0                       0   

        Pedestrian_Road_Maintenance_Worker  Casualty_Type  \
0                                        0              9   
1                                        0              9   
2                                        0              1   
3                                        0              0   
4                                        0              9   
...                                    ...            ...   
458843                                   0              0   
458844                                   0             19   
458845                                   0              4   
458846                                   0              9   
458847                                   0              9   

        Casualty_Home_Area_Type  Casualty_IMD_Decile  
0                      

In [5]:
df.describe() #Studying about the df

Vehicle_Reference  Casualty_Reference  Casualty_Class  Sex_of_Casualty  \
count      458848.000000       458848.000000   458848.000000    458848.000000   
mean            1.479895            1.392139        1.490801         1.405062   
std             1.601020            2.361797        0.727490         0.490905   
min             1.000000            1.000000        1.000000         1.000000   
25%             1.000000            1.000000        1.000000         1.000000   
50%             1.000000            1.000000        1.000000         1.000000   
75%             2.000000            1.000000        2.000000         2.000000   
max           999.000000          991.000000        3.000000         2.000000   

       Age_of_Casualty  Age_Band_of_Casualty  Casualty_Severity  \
count    458848.000000         458848.000000      458848.000000   
mean         37.497051              6.450504           2.818203   
std          19.069044              2.247572           0.413915   
min           0.000000              1.000000           1.000000   
25%          23.000000              5.000000           3.000000   
50%          34.000000              6.000000           3.000000   
75%          50.000000              8.000000           3.000000   
max         102.000000             11.000000           3.000000   

       Pedestrian_Location  Pedestrian_Movement  Car_Passenger  \
count        458848.000000        458848.000000  458848.000000   
mean              0.750979             0.590952       0.242950   
std               2.108936             1.906667       0.569136   
min               0.000000             0.000000      -1.000000   
25%               0.000000             0.000000       0.000000   
50%               0.000000             0.000000       0.000000   
75%               0.000000             0.000000       0.000000   
max              10.000000             9.000000       2.000000   

       Bus_or_Coach_Passenger  Pedestrian_Road_Maintenance_Worker  \
count           458848.000000                       458848.000000   
mean                 0.070322                            0.063649   
std                  0.503588                            0.350247   
min                  0.000000                            0.000000   
25%                  0.000000                            0.000000   
50%                  0.000000                            0.000000   
75%                  0.000000                            0.000000   
max                  4.000000                            2.000000   

       Casualty_Type  Casualty_Home_Area_Type  Casualty_IMD_Decile  
count  458848.000000            458848.000000        458848.000000  
mean        7.237013                 1.258231             3.855508  
std         8.166837                 0.613258             3.446473  
min         0.000000                 1.000000            -1.000000  
25%         2.000000                 1.000000             1.000000  
50%         9.000000                 1.000000             4.000000  
75%         9.000000                 1.000000             7.000000  
max        98.000000                 3.000000            10.000000

In [6]:
df.info() #Studying about the df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458848 entries, 0 to 458847
Data columns (total 16 columns):
 #   Column                              Non-Null Count   Dtype 
---  ------                              --------------   ----- 
 0   Accident_Index                      458848 non-null  object
 1   Vehicle_Reference                   458848 non-null  int64 
 2   Casualty_Reference                  458848 non-null  int64 
 3   Casualty_Class                      458848 non-null  int64 
 4   Sex_of_Casualty                     458848 non-null  int64 
 5   Age_of_Casualty                     458848 non-null  int64 
 6   Age_Band_of_Casualty                458848 non-null  int64 
 7   Casualty_Severity                   458848 non-null  int64 
 8   Pedestrian_Location                 458848 non-null  int64 
 9   Pedestrian_Movement                 458848 non-null  int64 
 10  Car_Passenger                       458848 non-null  int64 
 11  Bus_or_Coach_Passenger              458

In [7]:
X = df.loc[:, df.columns != 'Casualty_Severity'] 
#Casualty_Severity is the target column. We don't want to include this in the training data

X = X.loc[:, X.columns != 'Accident_Index']
#Accident_Index is key of the accident dataset. This is not a valid feature in training/testing data.

X = X.loc[:, X.columns != 'Casualty_Reference']
#Casualty_Reference is key of the casuality dataset. This is not a valid feature in training/testing data.


y = df['Casualty_Severity']

In [8]:
X #X dataset

Vehicle_Reference  Casualty_Class  Sex_of_Casualty  Age_of_Casualty  \
0                       1               1                1               58   
1                       1               1                2               24   
2                       2               2                2               21   
3                       1               3                1               68   
4                       1               1                2               47   
...                   ...             ...              ...              ...   
458843                  1               3                2               49   
458844                  1               2                1               22   
458845                  1               1                1               25   
458846                  1               1                1               49   
458847                  2               1                1               50   

        Age_Band_of_Casualty  Pedestrian_Location  Pedestrian_Movement  \
0                          9                    0                    0   
1                          5                    0                    0   
2                          5                    0                    0   
3                         10                    5                    4   
4                          8                    0                    0   
...                      ...                  ...                  ...   
458843                     8                    9                    6   
458844                     5                    0                    0   
458845                     5                    0                    0   
458846                     8                    0                    0   
458847                     8                    0                    0   

        Car_Passenger  Bus_or_Coach_Passenger  \
0                   0                       0   
1                   0                       0   
2                   0                       0   
3                   0                       0   
4                   0                       0   
...               ...                     ...   
458843              0                       0   
458844              1                       0   
458845              0                       0   
458846              0                       0   
458847              0                       0   

        Pedestrian_Road_Maintenance_Worker  Casualty_Type  \
0                                        0              9   
1                                        0              9   
2                                        0              1   
3                                        0              0   
4                                        0              9   
...                                    ...            ...   
458843                                   0              0   
458844                                   0             19   
458845                                   0              4   
458846                                   0              9   
458847                                   0              9   

        Casualty_Home_Area_Type  Casualty_IMD_Decile  
0                             1                    2  
1                             1                    3  
2                             1                    1  
3                             1                    4  
4                             1                    3  
...                         ...                  ...  
458843                        3                   -1  
458844                        1                    2  
458845                        1                   -1  
458846                        3                   -1  
458847                        2                   -1  

[458848 rows x 13 columns]

In [9]:
y #Target column

0         3
1         3
2         3
3         2
4         3
         ..
458843    3
458844    3
458845    3
458846    3
458847    2
Name: Casualty_Severity, Length: 458848, dtype: int64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Splitting the dataset X and y into X_train, X_tests, and y_train, y_tests correspondingly.
# Split ratio of 80:20% is used and random_state is used to produce the same datapoints every time (reproducible).

In [11]:
X_Pedestrian = df['Pedestrian_Location']
y_Pedestrian = df['Casualty_Severity']

X_Ped_train, X_Ped_test, y_Ped_train, y_Ped_test = train_test_split(X_Pedestrian, y_Pedestrian, test_size=0.2, random_state=42)


# Model 1: Logistic Regression - Accuracy 82.8%

***Testing with various values of C*** 

### ***Tested C values in [0.01, 0.1, 1]***

Got the same accuracy with all the C values

In [12]:
model = LogisticRegression(C=1, fit_intercept=True, intercept_scaling=1, solver='lbfgs', max_iter=10)
model.fit(X_train, y_train)

#When C = 0.1, accuracy 82.8%
#When C = 0.01, accuracy 82.8%
#When C = 1, accuracy 82.8%

LogisticRegression(C=1, max_iter=10)

In [13]:
# Now that the model learnt the data, we will try to predict y_pred for X_test

y_pred = model.predict(X_test)

In [14]:
# We got 82.8% accuracy of the predictions

accuracy_score(y_test, y_pred)

0.8282772147760706

In [15]:
y_pred.shape

# y_test.shape

(91770,)

In [16]:
print('\nLogistic Regression Accuracy: ' + str(accuracy_score(y_test, y_pred)*100))
print('Logistic Regression Classification report:\n', classification_report(y_test, y_pred))


Logistic Regression Accuracy: 82.82772147760707
Logistic Regression Classification report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00      1050
           2       0.00      0.00      0.00     14707
           3       0.83      1.00      0.91     76013

    accuracy                           0.83     91770
   macro avg       0.28      0.33      0.30     91770
weighted avg       0.69      0.83      0.75     91770



In [17]:
confusion_matrix(y_test, y_pred)

array([[    0,     0,  1050],
       [    0,     0, 14707],
       [    0,     2, 76011]])

# Model 2: Logistic Regression with 10-fold CV - Accuracy 82.94%

In [18]:
num_instances = len(X)
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = LogisticRegression()
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 82.949% (1.255%)


# Model 3: Random Forests with 10-Fold - Accuracy 82.028%

In [19]:
num_instances = len(X)
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = RandomForestClassifier()
results = model_selection.cross_val_score(model, X, y, cv=kfold)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 80.742% (1.040%)


In [20]:
# random forest model creation - for one instance
model = RandomForestClassifier()
model.fit(X_train,y_train)

# predictions
y_pred = model.predict(X_test)

In [21]:
y_pred.shape

(91770,)

In [22]:
print('Accuracy is: ' + str(accuracy_score(y_test, y_pred, normalize=True)*100) + '%')

Accuracy is: 80.66906396425847%


In [23]:
results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results)

Confusion Matrix :
[[    8   155   887]
 [   52  1638 13017]
 [  132  3497 72384]]


# Method 4: Polynomial Kernel SVM - Accuracy 82.82%

In [24]:
model = Pipeline([
        ("poly_features", PolynomialFeatures(degree=3)),
        ("scaler", MinMaxScaler()),
        ("svm_clf", LinearSVC(C=1, loss="hinge", random_state=42))
    ])


model.fit(X_train, y_train)

#y_test
y_pred = model.predict(X_test)


#Confusion Matrix
print('Polynomial Regression Accuracy: ' + str(accuracy_score(y_test, y_pred)*100))
print('Polynomial Regression Classification report:\n', classification_report(y_test, y_pred))

results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results) 

Polynomial Regression Accuracy: 82.82990083905416
Polynomial Regression Classification report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00      1050
           2       0.00      0.00      0.00     14707
           3       0.83      1.00      0.91     76013

    accuracy                           0.83     91770
   macro avg       0.28      0.33      0.30     91770
weighted avg       0.69      0.83      0.75     91770

Confusion Matrix :
[[    0     0  1050]
 [    1     0 14706]
 [    0     0 76013]]


# Method 5: LinearSVC - Accuracy 82.82%

In [25]:
# 1. Create an svm Classifier
model = svmClassifier2 = Pipeline([
    ("scaler", StandardScaler()), 
    ("linear_svc", LinearSVC(C=0.1, loss='hinge',random_state=42))])

#2. Train the model using the training sets - fit the model - with training data
model.fit(X_train, y_train)


Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc',
                 LinearSVC(C=0.1, loss='hinge', random_state=42))])

In [26]:
#To know if the model is overfitting or underfitting
y_train_pred = model.predict(X_test)

print('Linear SVM Training Accuracy: ' + str(accuracy_score(y_test, y_train_pred)*100))

Linear SVM Training Accuracy: 82.82990083905416


In [27]:
#3. Predict the response for test dataset - predict using the trained model for test data
y_pred = model.predict(X_test)

print('Linear SVM Accuracy: ' + str(accuracy_score(y_test, y_pred)*100))
print('Linear SVM Classification report:\n', classification_report(y_test, y_pred))

results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results) 

Linear SVM Accuracy: 82.82990083905416
Linear SVM Classification report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00      1050
           2       0.00      0.00      0.00     14707
           3       0.83      1.00      0.91     76013

    accuracy                           0.83     91770
   macro avg       0.28      0.33      0.30     91770
weighted avg       0.69      0.83      0.75     91770

Confusion Matrix :
[[    0     0  1050]
 [    0     0 14707]
 [    0     0 76013]]


# Method 6: Decision Tree Classifier - Accuracy 81.337%

In [28]:
# Decision Tree Classifier model
model = DecisionTreeClassifier()

# Training the model
model = model.fit(X_train,y_train)

#Predicting the results
y_pred = model.predict(X_test)

print('Decision Tree classifer : ' + str(accuracy_score(y_test, y_pred)*100))
print('Decision Tree Classification report:\n', classification_report(y_test, y_pred))

results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results)

Decision Tree classifer : 78.44393592677346
Decision Tree Classification report:
               precision    recall  f1-score   support

           1       0.04      0.03      0.03      1050
           2       0.28      0.16      0.21     14707
           3       0.84      0.91      0.88     76013

    accuracy                           0.78     91770
   macro avg       0.39      0.37      0.37     91770
weighted avg       0.74      0.78      0.76     91770

Confusion Matrix :
[[   29   224   797]
 [  188  2417 12102]
 [  463  6008 69542]]


# Model 7: SGD Classifier - Accuracy 81.33%

In [29]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(max_iter=1000, tol=1e-3, random_state=42)
sgd_clf.fit(X_train, y_train)

SGDClassifier(random_state=42)

In [30]:
sgd_clf.predict(X_test)

print('SGD classifer : ' + str(accuracy_score(y_test, y_pred)*100))
print('SGD Classification report:\n', classification_report(y_test, y_pred))

results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results)

SGD classifer : 78.44393592677346
SGD Classification report:
               precision    recall  f1-score   support

           1       0.04      0.03      0.03      1050
           2       0.28      0.16      0.21     14707
           3       0.84      0.91      0.88     76013

    accuracy                           0.78     91770
   macro avg       0.39      0.37      0.37     91770
weighted avg       0.74      0.78      0.76     91770

Confusion Matrix :
[[   29   224   797]
 [  188  2417 12102]
 [  463  6008 69542]]


# Model 8: OneVsRestClassifier SVC model - Accuracy 82.61%

In [31]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
ovr_clf = OneVsRestClassifier(SVC(gamma="auto", random_state=42))
ovr_clf.fit(X_train[:1000], y_train[:1000])
print(len(ovr_clf.estimators_))

y_pred = ovr_clf.predict(X_test)


3


In [32]:
print('SVM SVC One vs. All Classifer : ' + str(accuracy_score(y_test, y_pred)*100))
print('SVM SVC One vs. All Classification report:\n', classification_report(y_test, y_pred))

results = confusion_matrix(y_test, y_pred) 

print ("Confusion Matrix :")
print(results)

SVM SVC One vs. All Classifer : 82.62939958592132
SVM SVC One vs. All Classification report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00      1050
           2       0.30      0.01      0.02     14707
           3       0.83      1.00      0.90     76013

    accuracy                           0.83     91770
   macro avg       0.38      0.34      0.31     91770
weighted avg       0.73      0.83      0.75     91770

Confusion Matrix :
[[    0    13  1037]
 [   11   140 14556]
 [   10   314 75689]]


# Model 9: KNeighborsClassifier & GridSearchCV - Accuracy 80.38%

In [33]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

param_grid = [{'weights': ["uniform", "distance"], 'n_neighbors': [3, 5]}]

knn_clf = KNeighborsClassifier()
grid_search = GridSearchCV(knn_clf, param_grid, cv=3, verbose=3)
grid_search.fit(X_train, y_train)

grid_search.best_params_

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] n_neighbors=3, weights=uniform ..................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ...... n_neighbors=3, weights=uniform, score=0.783, total=  40.6s
[CV] n_neighbors=3, weights=uniform ..................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   40.6s remaining:    0.0s


[CV] ...... n_neighbors=3, weights=uniform, score=0.785, total=  33.5s
[CV] n_neighbors=3, weights=uniform ..................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  1.2min remaining:    0.0s


[CV] ...... n_neighbors=3, weights=uniform, score=0.785, total=  39.2s
[CV] n_neighbors=3, weights=distance .................................
[CV] ..... n_neighbors=3, weights=distance, score=0.771, total=  35.0s
[CV] n_neighbors=3, weights=distance .................................
[CV] ..... n_neighbors=3, weights=distance, score=0.774, total=  28.2s
[CV] n_neighbors=3, weights=distance .................................
[CV] ..... n_neighbors=3, weights=distance, score=0.774, total=  36.2s
[CV] n_neighbors=5, weights=uniform ..................................
[CV] ...... n_neighbors=5, weights=uniform, score=0.804, total=  39.9s
[CV] n_neighbors=5, weights=uniform ..................................
[CV] ...... n_neighbors=5, weights=uniform, score=0.805, total=  34.0s
[CV] n_neighbors=5, weights=uniform ..................................
[CV] ...... n_neighbors=5, weights=uniform, score=0.806, total=  40.6s
[CV] n_neighbors=5, weights=distance .................................
[CV] .

[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:  7.2min finished


{'n_neighbors': 5, 'weights': 'uniform'}

In [34]:
grid_search.best_score_

0.8050169201209848

In [35]:
from sklearn.metrics import accuracy_score

y_pred = grid_search.predict(X_test)
accuracy_score(y_test, y_pred)

0.8030620028331699

# Model 10: XGBoost - Accuracy 82.81%

In [36]:
import xgboost as xgb

clf = xgb.XGBClassifier(
 learning_rate =0.1,
 n_estimators=1000,
 max_depth=5,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'binary:logistic',
 nthread=4,
 scale_pos_weight=1,
 seed=27)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print('Accuracy is:' + str(accuracy_score(y_test, y_pred)))

[14:26:52] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:516: 
Parameters: { scale_pos_weight } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


Accuracy is:0.8284515636918383


# Model 11: AdaBoost - Accuracy 82.83%

In [37]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=1), n_estimators=200,
    algorithm="SAMME.R", learning_rate=0.5, random_state=42)
ada_clf.fit(X_train, y_train)

y_pred = ada_clf.predict(X_test)
print('Accuracy is:' + str(accuracy_score(y_test, y_pred)))

Accuracy is:0.8284079764628963


# Conclusions

So far, we have run and evalauted 11 popular classification models. <br><br>
***Logistic Regression with 10-fold CV (82.94% accuracy) and AdaBoost (82.83% accuracy) are the best performing models amongst all.***
<br>

Summary all the models:
1. Logistic Regression - Accuracy 82.8%
2. Logistic Regression with 10-fold CV - Accuracy 82.94%
3. Random Forests with 10-Fold - Accuracy 82.028%
4. Polynomial Kernel SVM - Accuracy 82.82%
5. LinearSVC - Accuracy 82.82%
6. Decision Tree Classifier - Accuracy 81.337%
7. SGD Classifier - Accuracy 81.33%
8. OneVsRestClassifier SVC model - Accuracy 82.61%
9. KNeighborsClassifier & GridSearchCV - Accuracy 80.38%
10. XGBoost - Accuracy 82.81%
11. AdaBoost - Accuracy 82.83%




1. Logistic Regression: (a.k.a Logit Regression)
This model is commonly used to estimate the probability of a prediction of a particular class.
When C=1, the logistic regression model gave an accuracy of 82.82%

We also evaluated the model by varying C values to 0.01, 0.1, and 1. All three experiments resulted in an accuracy of 82.82%.

2. Logistic Regression with 10-Fold Cross-Validation

In K Fold cross-validation (CV), the data is divided into k subsets. Now the holdout method is repeated k times, such that each time, one of the k subsets is used as the test set/ validation set and the other k-1 subsets are put together to form a training set. [4]

In this step, we used 10-Fold CV achieved an accuracy of 82.94%

3. Random Forests with 10-Fold Cross-Validation

An ensemble learning method for classification, random forest classifier achieved an accuracy of 82.028%

4. Polynomial Kernel SVM, of degree = 3

We used a degree of 3 polynomial SVM for this data. This gave an accuracy of 82.82%

5. LinearSVC

In LinearSVC, the algorithm aims to get the ‘best fit’ hyperplane that classifies the data. In this step, we achieved an accuracy of 82.82%. 

6. Decision Tree Classifier	

A decision tree classifier builds the model in the form of a tree structure. This tree has decision nodes and leaf nodes. We used a decision tree classifier for our problem and got an accuracy of 81.337%.

7. SGD Classifier	

Stochastic Gradient Descent (SGD) classifier is a widely popular algorithm for its ease of use and efficiency. In this step, we achieved an accuracy of 81.33% 

8. OneVsRestClassifier SVC model	

Also known as one-vs-all, this strategy consists of fitting one classifier per class. For each classifier, the class is fitted against all the other classes. In addition to its computational efficiency (only n_classes classifiers are needed), one advantage of this approach is its interpretability. [5]

In this step, we achieved an accuracy of 82.61%

9. KNeighborsClassifier & GridSearchCV

KNeighborsClassifier is implemented based on a k-nearest neighbor vote. In this step, we achieved an accuracy of 80.38%

10. XGBoost 
XGBoost, which provides parallel tree boosting, is one of the most popular machine learning models in recent years. We used XGBoost for this problem and achieved an accuracy of 82.81%.

11. AdaBoost 

AdaBoost iteratively learns from the mistakes of weak classifiers, and tries to turn them into strong ones. In this step, we achieved an accuracy of 82.83%


References

1. https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html
2. Hyperparameter tuning in SGD and Logistic Classifiers: <br>
   https://www.knowledgehut.com/tutorials/machine-learning/hyperparameter-tuning-machine-learning